//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TblVacation", Namespace="http://schemas.datacontract.org/2004/07/EmployeesPayrollWebService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class TblVacation : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ApprovedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ApprovedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CSPVACATIONIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DAYSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmplidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FromDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IserialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ToDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ApprovedBy {
            get {
                return this.ApprovedByField;
            }
            set {
                this.ApprovedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ApprovedDate {
            get {
                return this.ApprovedDateField;
            }
            set {
                this.ApprovedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CSPVACATIONID {
            get {
                return this.CSPVACATIONIDField;
            }
            set {
                this.CSPVACATIONIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                this.CreationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DAYS {
            get {
                return this.DAYSField;
            }
            set {
                this.DAYSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Emplid {
            get {
                return this.EmplidField;
            }
            set {
                this.EmplidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FromDate {
            get {
                return this.FromDateField;
            }
            set {
                this.FromDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Iserial {
            get {
                return this.IserialField;
            }
            set {
                this.IserialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ToDate {
            get {
                return this.ToDateField;
            }
            set {
                this.ToDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TblVariableTermManual", Namespace="http://schemas.datacontract.org/2004/07/EmployeesPayrollWebService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class TblVariableTermManual : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmplidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> HoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IserialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CCWFM.Web.ServiceReference1.TblSalaryTerm TblSalaryTermField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.Objects.DataClasses.EntityReference<CCWFM.Web.ServiceReference1.TblSalaryTerm> TblSalaryTermReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TermIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TransDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Days {
            get {
                return this.DaysField;
            }
            set {
                this.DaysField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Emplid {
            get {
                return this.EmplidField;
            }
            set {
                this.EmplidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Hours {
            get {
                return this.HoursField;
            }
            set {
                this.HoursField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Iserial {
            get {
                return this.IserialField;
            }
            set {
                this.IserialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CCWFM.Web.ServiceReference1.TblSalaryTerm TblSalaryTerm {
            get {
                return this.TblSalaryTermField;
            }
            set {
                this.TblSalaryTermField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReference<CCWFM.Web.ServiceReference1.TblSalaryTerm> TblSalaryTermReference {
            get {
                return this.TblSalaryTermReferenceField;
            }
            set {
                this.TblSalaryTermReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TermId {
            get {
                return this.TermIdField;
            }
            set {
                this.TermIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TransDate {
            get {
                return this.TransDateField;
            }
            set {
                this.TransDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TblSalaryTerm", Namespace="http://schemas.datacontract.org/2004/07/EmployeesPayrollWebService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class TblSalaryTerm : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IserialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CCWFM.Web.ServiceReference1.TblVariableTermManual> TblVariableTermManualsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Aname {
            get {
                return this.AnameField;
            }
            set {
                this.AnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ename {
            get {
                return this.EnameField;
            }
            set {
                this.EnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Iserial {
            get {
                return this.IserialField;
            }
            set {
                this.IserialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CCWFM.Web.ServiceReference1.TblVariableTermManual> TblVariableTermManuals {
            get {
                return this.TblVariableTermManualsField;
            }
            set {
                this.TblVariableTermManualsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TblEmployeeShiftLookup", Namespace="http://schemas.datacontract.org/2004/07/EmployeesPayrollWebService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class TblEmployeeShiftLookup : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CalendarIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IserialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShiftField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<CCWFM.Web.ServiceReference1.TblEmployeeShift> TblEmployeeShiftsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CalendarId {
            get {
                return this.CalendarIdField;
            }
            set {
                this.CalendarIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Iserial {
            get {
                return this.IserialField;
            }
            set {
                this.IserialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Shift {
            get {
                return this.ShiftField;
            }
            set {
                this.ShiftField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<CCWFM.Web.ServiceReference1.TblEmployeeShift> TblEmployeeShifts {
            get {
                return this.TblEmployeeShiftsField;
            }
            set {
                this.TblEmployeeShiftsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TblExcuse", Namespace="http://schemas.datacontract.org/2004/07/EmployeesPayrollWebService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class TblExcuse : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ApprovedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ApprovedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CSPEXCUSEIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmplidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FromTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IserialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ToTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TransDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ApprovedBy {
            get {
                return this.ApprovedByField;
            }
            set {
                this.ApprovedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ApprovedDate {
            get {
                return this.ApprovedDateField;
            }
            set {
                this.ApprovedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CSPEXCUSEID {
            get {
                return this.CSPEXCUSEIDField;
            }
            set {
                this.CSPEXCUSEIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                this.CreationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Emplid {
            get {
                return this.EmplidField;
            }
            set {
                this.EmplidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FromTime {
            get {
                return this.FromTimeField;
            }
            set {
                this.FromTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Iserial {
            get {
                return this.IserialField;
            }
            set {
                this.IserialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ToTime {
            get {
                return this.ToTimeField;
            }
            set {
                this.ToTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TransDate {
            get {
                return this.TransDateField;
            }
            set {
                this.TransDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TblMission", Namespace="http://schemas.datacontract.org/2004/07/EmployeesPayrollWebService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class TblMission : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ApprovedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ApprovedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CSPMISSIONIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmplidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FromDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FromTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IserialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ToDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ToTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ApprovedBy {
            get {
                return this.ApprovedByField;
            }
            set {
                this.ApprovedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ApprovedDate {
            get {
                return this.ApprovedDateField;
            }
            set {
                this.ApprovedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CSPMISSIONID {
            get {
                return this.CSPMISSIONIDField;
            }
            set {
                this.CSPMISSIONIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                this.CreationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Emplid {
            get {
                return this.EmplidField;
            }
            set {
                this.EmplidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FromDate {
            get {
                return this.FromDateField;
            }
            set {
                this.FromDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FromTime {
            get {
                return this.FromTimeField;
            }
            set {
                this.FromTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Iserial {
            get {
                return this.IserialField;
            }
            set {
                this.IserialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ToDate {
            get {
                return this.ToDateField;
            }
            set {
                this.ToDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ToTime {
            get {
                return this.ToTimeField;
            }
            set {
                this.ToTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TblAttendanceFile", Namespace="http://schemas.datacontract.org/2004/07/EmployeesPayrollWebService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class TblAttendanceFile : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ApprovedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ApprovedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmplidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FromTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IserialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OrginalFromTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OrginalInTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TblAttendanceFileReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ToTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TransDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ApprovedBy {
            get {
                return this.ApprovedByField;
            }
            set {
                this.ApprovedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ApprovedDate {
            get {
                return this.ApprovedDateField;
            }
            set {
                this.ApprovedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                this.CreationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Emplid {
            get {
                return this.EmplidField;
            }
            set {
                this.EmplidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FromTime {
            get {
                return this.FromTimeField;
            }
            set {
                this.FromTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Iserial {
            get {
                return this.IserialField;
            }
            set {
                this.IserialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OrginalFromTime {
            get {
                return this.OrginalFromTimeField;
            }
            set {
                this.OrginalFromTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OrginalInTime {
            get {
                return this.OrginalInTimeField;
            }
            set {
                this.OrginalInTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TblAttendanceFileReason {
            get {
                return this.TblAttendanceFileReasonField;
            }
            set {
                this.TblAttendanceFileReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ToTime {
            get {
                return this.ToTimeField;
            }
            set {
                this.ToTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TransDate {
            get {
                return this.TransDateField;
            }
            set {
                this.TransDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TblEmployeeShift", Namespace="http://schemas.datacontract.org/2004/07/EmployeesPayrollWebService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class TblEmployeeShift : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IserialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TblEmployeeShiftLookupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CCWFM.Web.ServiceReference1.TblEmployeeShiftLookup TblEmployeeShiftLookup1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.Objects.DataClasses.EntityReference<CCWFM.Web.ServiceReference1.TblEmployeeShiftLookup> TblEmployeeShiftLookup1ReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TblStoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TransDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WeekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Day {
            get {
                return this.DayField;
            }
            set {
                this.DayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpId {
            get {
                return this.EmpIdField;
            }
            set {
                this.EmpIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Iserial {
            get {
                return this.IserialField;
            }
            set {
                this.IserialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TblEmployeeShiftLookup {
            get {
                return this.TblEmployeeShiftLookupField;
            }
            set {
                this.TblEmployeeShiftLookupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CCWFM.Web.ServiceReference1.TblEmployeeShiftLookup TblEmployeeShiftLookup1 {
            get {
                return this.TblEmployeeShiftLookup1Field;
            }
            set {
                this.TblEmployeeShiftLookup1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReference<CCWFM.Web.ServiceReference1.TblEmployeeShiftLookup> TblEmployeeShiftLookup1Reference {
            get {
                return this.TblEmployeeShiftLookup1ReferenceField;
            }
            set {
                this.TblEmployeeShiftLookup1ReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TblStore {
            get {
                return this.TblStoreField;
            }
            set {
                this.TblStoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TransDate {
            get {
                return this.TransDateField;
            }
            set {
                this.TransDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Week {
            get {
                return this.WeekField;
            }
            set {
                this.WeekField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                this.YearField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ServiceReference1.EmployeePayrollService")]
    public interface EmployeePayrollService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:EmployeePayrollService/InsertEmpVacation", ReplyAction="urn:EmployeePayrollService/InsertEmpVacationResponse")]
        void InsertEmpVacation(System.Collections.Generic.List<CCWFM.Web.ServiceReference1.TblVacation> vacations);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:EmployeePayrollService/DeleteEmpVacation", ReplyAction="urn:EmployeePayrollService/DeleteEmpVacationResponse")]
        void DeleteEmpVacation(string emp, System.DateTime Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:EmployeePayrollService/InsertVariableTerm", ReplyAction="urn:EmployeePayrollService/InsertVariableTermResponse")]
        void InsertVariableTerm(CCWFM.Web.ServiceReference1.TblVariableTermManual row, CCWFM.Web.ServiceReference1.TblVariableTermManual oldRow);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:EmployeePayrollService/DeleteVariableTerm", ReplyAction="urn:EmployeePayrollService/DeleteVariableTermResponse")]
        void DeleteVariableTerm(string emp, System.DateTime Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:EmployeePayrollService/DeleteEmpExcuse", ReplyAction="urn:EmployeePayrollService/DeleteEmpExcuseResponse")]
        void DeleteEmpExcuse(string emp, System.DateTime Date, int FromTime, int ToTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:EmployeePayrollService/InsertEmpExcuse", ReplyAction="urn:EmployeePayrollService/InsertEmpExcuseResponse")]
        void InsertEmpExcuse(System.Collections.Generic.List<CCWFM.Web.ServiceReference1.TblExcuse> excuses, System.Collections.Generic.List<CCWFM.Web.ServiceReference1.TblExcuse> OldExcuses);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:EmployeePayrollService/DeleteEmpMission", ReplyAction="urn:EmployeePayrollService/DeleteEmpMissionResponse")]
        void DeleteEmpMission(string emp, System.DateTime Date, int FromTime, int ToTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:EmployeePayrollService/InsertEmpMission", ReplyAction="urn:EmployeePayrollService/InsertEmpMissionResponse")]
        void InsertEmpMission(System.Collections.Generic.List<CCWFM.Web.ServiceReference1.TblMission> missions, System.Collections.Generic.List<CCWFM.Web.ServiceReference1.TblMission> OldMission);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:EmployeePayrollService/DeleteAttFile", ReplyAction="urn:EmployeePayrollService/DeleteAttFileResponse")]
        void DeleteAttFile(string emp, System.DateTime Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:EmployeePayrollService/InsertAttFile", ReplyAction="urn:EmployeePayrollService/InsertAttFileResponse")]
        void InsertAttFile(System.Collections.Generic.List<CCWFM.Web.ServiceReference1.TblAttendanceFile> AttendanceFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:EmployeePayrollService/InsertEmpCalendarDeviationNoExist", ReplyAction="urn:EmployeePayrollService/InsertEmpCalendarDeviationNoExistResponse")]
        void InsertEmpCalendarDeviationNoExist();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:EmployeePayrollService/InsertEmpMissionNoExist", ReplyAction="urn:EmployeePayrollService/InsertEmpMissionNoExistResponse")]
        void InsertEmpMissionNoExist();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:EmployeePayrollService/InsertEmpAttNoExist", ReplyAction="urn:EmployeePayrollService/InsertEmpAttNoExistResponse")]
        void InsertEmpAttNoExist();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:EmployeePayrollService/InsertEmpExcuseNoExist", ReplyAction="urn:EmployeePayrollService/InsertEmpExcuseNoExistResponse")]
        void InsertEmpExcuseNoExist();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:EmployeePayrollService/InsertEmpVacationNoExist", ReplyAction="urn:EmployeePayrollService/InsertEmpVacationNoExistResponse")]
        void InsertEmpVacationNoExist();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:EmployeePayrollService/InsertEmpCalendarDeviation", ReplyAction="urn:EmployeePayrollService/InsertEmpCalendarDeviationResponse")]
        void InsertEmpCalendarDeviation(System.Collections.Generic.List<CCWFM.Web.ServiceReference1.TblEmployeeShift> employeeShifts);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:EmployeePayrollService/DeleteEmpCalendarDeviation", ReplyAction="urn:EmployeePayrollService/DeleteEmpCalendarDeviationResponse")]
        void DeleteEmpCalendarDeviation(string emp, System.DateTime Date, string calen);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmployeePayrollServiceChannel : CCWFM.Web.ServiceReference1.EmployeePayrollService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeePayrollServiceClient : System.ServiceModel.ClientBase<CCWFM.Web.ServiceReference1.EmployeePayrollService>, CCWFM.Web.ServiceReference1.EmployeePayrollService {
        
        public EmployeePayrollServiceClient() {
        }
        
        public EmployeePayrollServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeePayrollServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeePayrollServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeePayrollServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertEmpVacation(System.Collections.Generic.List<CCWFM.Web.ServiceReference1.TblVacation> vacations) {
            base.Channel.InsertEmpVacation(vacations);
        }
        
        public void DeleteEmpVacation(string emp, System.DateTime Date) {
            base.Channel.DeleteEmpVacation(emp, Date);
        }
        
        public void InsertVariableTerm(CCWFM.Web.ServiceReference1.TblVariableTermManual row, CCWFM.Web.ServiceReference1.TblVariableTermManual oldRow) {
            base.Channel.InsertVariableTerm(row, oldRow);
        }
        
        public void DeleteVariableTerm(string emp, System.DateTime Date) {
            base.Channel.DeleteVariableTerm(emp, Date);
        }
        
        public void DeleteEmpExcuse(string emp, System.DateTime Date, int FromTime, int ToTime) {
            base.Channel.DeleteEmpExcuse(emp, Date, FromTime, ToTime);
        }
        
        public void InsertEmpExcuse(System.Collections.Generic.List<CCWFM.Web.ServiceReference1.TblExcuse> excuses, System.Collections.Generic.List<CCWFM.Web.ServiceReference1.TblExcuse> OldExcuses) {
            base.Channel.InsertEmpExcuse(excuses, OldExcuses);
        }
        
        public void DeleteEmpMission(string emp, System.DateTime Date, int FromTime, int ToTime) {
            base.Channel.DeleteEmpMission(emp, Date, FromTime, ToTime);
        }
        
        public void InsertEmpMission(System.Collections.Generic.List<CCWFM.Web.ServiceReference1.TblMission> missions, System.Collections.Generic.List<CCWFM.Web.ServiceReference1.TblMission> OldMission) {
            base.Channel.InsertEmpMission(missions, OldMission);
        }
        
        public void DeleteAttFile(string emp, System.DateTime Date) {
            base.Channel.DeleteAttFile(emp, Date);
        }
        
        public void InsertAttFile(System.Collections.Generic.List<CCWFM.Web.ServiceReference1.TblAttendanceFile> AttendanceFile) {
            base.Channel.InsertAttFile(AttendanceFile);
        }
        
        public void InsertEmpCalendarDeviationNoExist() {
            base.Channel.InsertEmpCalendarDeviationNoExist();
        }
        
        public void InsertEmpMissionNoExist() {
            base.Channel.InsertEmpMissionNoExist();
        }
        
        public void InsertEmpAttNoExist() {
            base.Channel.InsertEmpAttNoExist();
        }
        
        public void InsertEmpExcuseNoExist() {
            base.Channel.InsertEmpExcuseNoExist();
        }
        
        public void InsertEmpVacationNoExist() {
            base.Channel.InsertEmpVacationNoExist();
        }
        
        public void InsertEmpCalendarDeviation(System.Collections.Generic.List<CCWFM.Web.ServiceReference1.TblEmployeeShift> employeeShifts) {
            base.Channel.InsertEmpCalendarDeviation(employeeShifts);
        }
        
        public void DeleteEmpCalendarDeviation(string emp, System.DateTime Date, string calen) {
            base.Channel.DeleteEmpCalendarDeviation(emp, Date, calen);
        }
    }
}
