//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.DataLayer
{
    using System;
    using System.Collections.Generic;using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    
    
    //[DataContract]
    public partial class AXRoute : PropertiesViewModelBase
    {
        public string StyleCode { get; set; }
        public string SalesOrderID { get; set; }
        public Nullable<double> RowIndex { get; set; }
        public string OperationCode { get; set; }
        public string WorkCenterCode { get; set; }
        public string vendorcode { get; set; }
        public Nullable<double> NextOperation { get; set; }
        public Nullable<double> BOM_OPR_OprCost { get; set; }
    }
}
