//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.DataLayer
{
    using System;
    using System.Collections.Generic;using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    
    
    //[DataContract]
    public partial class BarCodePrintLayout : PropertiesViewModelBase
    {
        public int BarcodeDisplaySettingsHeader { get; set; }
        public Nullable<double> FontSize { get; set; }
        public Nullable<bool> BoldProperty { get; set; }
        public Nullable<bool> ItalicProperty { get; set; }
        public double CanvasTop { get; set; }
        public double CanvasLeft { get; set; }
        public string FontFamily { get; set; }
        public int Iserial { get; set; }
        public Nullable<int> printingPropertiesIserial { get; set; }
        public string PropertyName { get; set; }
        public string PropertyNameArabic { get; set; }
        public string PropertyType { get; set; }
        public int printingCode { get; set; }
        public string Code { get; set; }
        public double BarcodeHeight { get; set; }
        public double BarcodeWidth { get; set; }
        public string PrintingBarcodeFormate { get; set; }
        public int BarcodeOperation { get; set; }
        public Nullable<double> PageHeight { get; set; }
        public Nullable<double> PageWidth { get; set; }
        public string PageSizeUnit { get; set; }
    }
}
