//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.DataLayer
{
    using System;
    using System.Collections.Generic;using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    
    
    //[DataContract]
    public partial class Brand : PropertiesViewModelBase
    {
        public string Brand_Code { get; set; }
        public string Brand_Ename { get; set; }
        public decimal ProfitMargin { get; set; }
        public int IsRetailBrand { get; set; }
        public string CustomerCode { get; set; }
        public string RETAILSUPPLIERCODE { get; set; }
    }
}
