//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.DataLayer
{
    using System;
    using System.Collections.Generic;using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    
    
    //[DataContract]
    public partial class DefectsData : PropertiesViewModelBase
    {
        public string Ename { get; set; }
        public string Aname { get; set; }
        public int DefectValue { get; set; }
        public int Iserial { get; set; }
        public int HeaderIserial { get; set; }
    }
}
