//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.DataLayer
{
    using System;
    using System.Collections.Generic;using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    
    
    //[DataContract]
    public partial class DhWomenFamily : PropertiesViewModelBase
    {
        public int TblClass1 { get; set; }
        public int tblClass2 { get; set; }
        public string FamilyCode { get; set; }
        public string FamilyName { get; set; }
        public string SubFamilyCode { get; set; }
        public string SubFamilyName { get; set; }
    }
}
