//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.DataLayer
{
    using System;
    using System.Collections.Generic;using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    
    
    //[DataContract]
    public partial class Employee : PropertiesViewModelBase
    {
        public string EMPLID { get; set; }
        public int CSPNoAttendance { get; set; }
        public string name { get; set; }
        public string OrganizationUnitId { get; set; }
        public string PARTYID { get; set; }
        public string Email { get; set; }
        public string MangerEmail { get; set; }
        public string CSPPERIODID { get; set; }
        public Nullable<int> EmpOnBehalf { get; set; }
    }
}
