//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.DataLayer
{
    using System;
    using System.Collections.Generic;using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    
    
    //[DataContract]
    public partial class FabricInventDimDetail : PropertiesViewModelBase
    {
        public string PURCHID { get; set; }
        public string Fabric_Code { get; set; }
        public string Fabric_Ename { get; set; }
        public decimal LINENUM { get; set; }
        public decimal LINEAMOUNT { get; set; }
        public string PURCHUNIT { get; set; }
        public string VENDACCOUNT { get; set; }
        public decimal PURCHQTY { get; set; }
        public string INVENTBATCHID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Color_Code { get; set; }
        public string DATAAREAID { get; set; }
    }
}
