//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.DataLayer
{
    using System;
    using System.Collections.Generic;using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    
    
    //[DataContract]
    public partial class FabricB : PropertiesViewModelBase
    {
        public string Fabric_Code { get; set; }
        public string Fabric_Ename { get; set; }
        public string Fabric_FabricType { get; set; }
        public Nullable<decimal> Fabric_Ecost { get; set; }
        public Nullable<decimal> Fabric_Acost { get; set; }
        public string Fabric_Vendor { get; set; }
        public string UnitID { get; set; }
        public string DATAAREAID { get; set; }
    }
}
