//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.DataLayer
{
    using System;
    using System.Collections.Generic;using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    
    
    //[DataContract]
    public partial class FabricInventSumWithBatch : PropertiesViewModelBase
    {
        public string FabricCode { get; set; }
        public decimal AVAILPHYSICAL { get; set; }
        public string INVENTDIMID { get; set; }
        public string CONFIGID { get; set; }
        public string INVENTBATCHID { get; set; }
        public string INVENTLOCATIONID { get; set; }
        public string INVENTSIZEID { get; set; }
        public string INVENTSITEID { get; set; }
        public string DATAAREAID { get; set; }
        public string LocationName { get; set; }
        public string SiteName { get; set; }
    }
}
