//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.DataLayer
{
    using System;
    using System.Collections.Generic;using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    
    
    //[DataContract]
    public partial class FabricInspectionPurchaseOrder : PropertiesViewModelBase
    {
        public System.DateTime DELIVERYDATE { get; set; }
        public string Fabric_Code { get; set; }
        public string BatchNo { get; set; }
        public string ColorCode { get; set; }
        public System.DateTime TransDate { get; set; }
        public string Vendor { get; set; }
        public string Unit { get; set; }
        public int RollNo { get; set; }
        public float StoreRollQty { get; set; }
        public Nullable<double> DefectsQty { get; set; }
        public Nullable<double> NetRollQty { get; set; }
        public float RemainingReservationRollQty { get; set; }
        public int HeaderIserial { get; set; }
        public string FinishedWarehouse { get; set; }
        public string FinishedLocation { get; set; }
        public string FinishedSite { get; set; }
        public short Degree { get; set; }
        public string TransOrder { get; set; }
        public int TransactionType { get; set; }
        public int Iserial { get; set; }
        public decimal LINENUM { get; set; }
        public float RemainingMarkerRollQty { get; set; }
        public string BARCODE { get; set; }
    }
}
