//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.DataLayer
{
    using System;
    using System.Collections.Generic;using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    
    
    //[DataContract]
    public partial class InventoryReservedJournalsDetail : PropertiesViewModelBase
    {
        public string JOURNALID { get; set; }
        public decimal LINENUM { get; set; }
        public System.DateTime TRANSDATE { get; set; }
        public string VOUCHER { get; set; }
        public int JOURNALTYPE { get; set; }
        public string ITEMID { get; set; }
        public decimal QTY { get; set; }
        public decimal COSTPRICE { get; set; }
        public decimal PRICEUNIT { get; set; }
        public decimal COSTMARKUP { get; set; }
        public decimal COSTAMOUNT { get; set; }
        public decimal SALESAMOUNT { get; set; }
        public string PROJTRANSID { get; set; }
        public string INVENTTRANSID { get; set; }
        public string INVENTTRANSIDFATHER { get; set; }
        public string LEDGERACCOUNTIDOFFSET { get; set; }
        public decimal INVENTONHAND { get; set; }
        public decimal COUNTED { get; set; }
        public string DIMENSION { get; set; }
        public string DIMENSION2_ { get; set; }
        public string DIMENSION3_ { get; set; }
        public int BOMLINE { get; set; }
        public string INVENTTRANSIDRETURN { get; set; }
        public string PROJCATEGORYID { get; set; }
        public string PROJID { get; set; }
        public string TOINVENTTRANSID { get; set; }
        public long REASONREFRECID { get; set; }
        public string INVENTDIMID { get; set; }
        public string TOINVENTDIMID { get; set; }
        public string REQPOID { get; set; }
        public string EMPLID { get; set; }
        public int ASSETTRANSTYPE { get; set; }
        public string ASSETID { get; set; }
        public string ASSETBOOKID { get; set; }
        public string PROJTAXGROUPID { get; set; }
        public string PROJSALESCURRENCYID { get; set; }
        public string PROJLINEPROPERTYID { get; set; }
        public string PROJTAXITEMGROUPID { get; set; }
        public string PROJUNITID { get; set; }
        public decimal PROJSALESPRICE { get; set; }
        public int INVENTREFTYPE { get; set; }
        public string INVENTREFID { get; set; }
        public string INVENTREFTRANSID { get; set; }
        public string ACTIVITYNUMBER { get; set; }
        public System.DateTime RELEASEDATE { get; set; }
        public int RELEASEDATETZID { get; set; }
        public string DATAAREAID { get; set; }
        public int RECVERSION { get; set; }
        public long RECID { get; set; }
        public int PROFITSET { get; set; }
        public string DEL_CORRECTIVEREASON { get; set; }
        public string DEL_CORRECTEDINVOICEID { get; set; }
        public string CLEHINT { get; set; }
        public string STYLE { get; set; }
        public string Unit { get; set; }
        public string FabricDescription { get; set; }
        public string FabricDescriptionAR { get; set; }
    }
}
