//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.DataLayer
{
    using System;
    using System.Collections.Generic;using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    
    
    //[DataContract]
    public partial class LocalBOM : PropertiesViewModelBase
    {
        public string SalesOrderCode { get; set; }
        public string BOM_Fabric { get; set; }
        public string BOM_FabricType { get; set; }
        public string StyleCode { get; set; }
        public string UnitID { get; set; }
        public string FabricColor { get; set; }
        public string Brand { get; set; }
        public string season { get; set; }
        public Nullable<double> MaxConsumption { get; set; }
        public string FabricColorName { get; set; }
        public string StyleColorCode { get; set; }
        public string StyleColorName { get; set; }
        public string OprID { get; set; }
        public string FabricSize { get; set; }
        public string PerSeries { get; set; }
    }
}
