//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.DataLayer
{
    using System;
    using System.Collections.Generic;using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    
    
    //[DataContract]
    public partial class LocalRoute : PropertiesViewModelBase
    {
        public string Style { get; set; }
        public string SalesOrder { get; set; }
        public Nullable<double> OprID { get; set; }
        public string OprName { get; set; }
        public string WorkCenter { get; set; }
        public Nullable<int> Time { get; set; }
        public Nullable<int> Qty { get; set; }
    }
}
