//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.DataLayer
{
    using System;
    using System.Collections.Generic;using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    
    
    //[DataContract]
    public partial class MarkerDetail : PropertiesViewModelBase
    {
        public int Iserial { get; set; }
        public string MarkerNo { get; set; }
        public string SalesOrder { get; set; }
        public string FabricCode { get; set; }
        public int StyleColorCode { get; set; }
        public int FabricColorCode { get; set; }
        public string StyleNo { get; set; }
        public string BatchNo { get; set; }
        public double MarkerL { get; set; }
        public double MarkerW { get; set; }
        public string SizeRange { get; set; }
        public double CloretteCmPerPc { get; set; }
        public int MarkerTransactionHeader { get; set; }
        public Nullable<double> TotalReq { get; set; }
        public Nullable<int> Status { get; set; }
        public string StyleColorName { get; set; }
        public string FabricColorName { get; set; }
    }
}
