//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.DataLayer
{
    using System;
    using System.Collections.Generic;using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    
    
    //[DataContract]
    public partial class MarkerReportSecondPartStoredProc : PropertiesViewModelBase
    {
        public Nullable<int> TotalDefectValue { get; set; }
        public Nullable<float> qtyOfDefects { get; set; }
        public Nullable<double> TotalMeterPerSizeValue { get; set; }
        public Nullable<int> MarkerIserial { get; set; }
        public string Model { get; set; }
        public string BatchNo { get; set; }
        public string MarkerNo { get; set; }
        public Nullable<double> MarkerL { get; set; }
        public Nullable<double> MarkerW { get; set; }
        public string SizeRange { get; set; }
        public string FabricColor { get; set; }
        public Nullable<int> fabricColorIserial { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<float> RollQtySecondPart { get; set; }
        public Nullable<int> RollNo { get; set; }
        public Nullable<float> RollWMT { get; set; }
        public Nullable<float> M2WeightGm { get; set; }
        public Nullable<float> ConsPerPC { get; set; }
        public Nullable<float> StoreRollQty { get; set; }
        public string RollStoreUnit { get; set; }
        public string RollUnit { get; set; }
        public Nullable<double> CloretteCmPerPc { get; set; }
        public Nullable<float> NoofPCs { get; set; }
        public string CuttingSelection { get; set; }
        public Nullable<double> RollAssignedQtyWithoutDefects { get; set; }
        public Nullable<int> MarkerTransactionHeader { get; set; }
        public string WareHouses { get; set; }
        public Nullable<int> Workstation { get; set; }
        public Nullable<float> QtyOfDefectCons { get; set; }
        public Nullable<double> TotalReq { get; set; }
        public Nullable<double> RollNoofPieces { get; set; }
        public string Fabric_Ename { get; set; }
        public string SalesOrder { get; set; }
        public Nullable<int> SalesOrderIserial { get; set; }
        public string FabricCode { get; set; }
        public string StyleNo { get; set; }
        public Nullable<int> StyleColorIserial { get; set; }
        public string StyleColorCode { get; set; }
        public string Vendor { get; set; }
        public string RollBatch { get; set; }
        public Nullable<double> ConsPerPCMT { get; set; }
        public Nullable<int> Total { get; set; }
        public string MeterPerSizeCode { get; set; }
        public Nullable<double> MeterPerSizeValue { get; set; }
        public Nullable<int> SizeCode_Id { get; set; }
        public Nullable<double> BomMaterialUsage { get; set; }
        public Nullable<double> SumRollQty { get; set; }
    }
}
