//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.DataLayer
{
    using System;
    using System.Collections.Generic;using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    
    
    //[DataContract]
    public partial class PrintingFabricDefect : PropertiesViewModelBase
    {
        public string Fabric_Code { get; set; }
        public int Tbl_fabricInspectionHeader { get; set; }
        public string ColorCode { get; set; }
        public Nullable<float> RollWMT { get; set; }
        public string BATCHID { get; set; }
        public string NetRollQty { get; set; }
        public string FabricDescriptionAR { get; set; }
        public string FabricDescription { get; set; }
        public Nullable<float> M2WeightGm { get; set; }
        public int Iserial { get; set; }
        public short Degree { get; set; }
        public string Batchno { get; set; }
    }
}
