//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.DataLayer
{
    using System;
    using System.Collections.Generic;using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    
    
    //[DataContract]
    public partial class RawFabricListReport : PropertiesViewModelBase
    {
        public string Code { get; set; }
        public string FabricDescription { get; set; }
        public string FabricMaterial { get; set; }
        public string FabricType { get; set; }
        public string Status { get; set; }
    }
}
