//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.DataLayer
{
    using System;
    using System.Collections.Generic;using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    
    
    //[DataContract]
    public partial class RealRoutCard : PropertiesViewModelBase
    {
        public int TransID { get; set; }
        public string StyleHeader { get; set; }
        public string SalesOrder { get; set; }
        public string Color { get; set; }
        public Nullable<int> Qty { get; set; }
        public string WorkStation { get; set; }
        public string Operation { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<System.Guid> Id { get; set; }
        public int HeaderIserial { get; set; }
        public int Direction { get; set; }
    }
}
