//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.DataLayer
{
    using System;
    using System.Collections.Generic;using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    
    
    //[DataContract]
    public partial class TblAuthUser : PropertiesViewModelBase
    {
        public TblAuthUser()
        {
            this.TblAdjustmentHeaders = new Collection<TblAdjustmentHeader>();
            this.TblAdjustmentHeaders1 = new Collection<TblAdjustmentHeader>();
            this.TblAuthWarehouses = new Collection<TblAuthWarehouse>();
            this.TblTransferHeaders = new Collection<TblTransferHeader>();
            this.TblTransferHeaders1 = new Collection<TblTransferHeader>();
            this.TblTransferHeaders2 = new Collection<TblTransferHeader>();
        }
    
        public int Iserial { get; set; }
        public string Code { get; set; }
        public string Aname { get; set; }
        public string Ename { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Address { get; set; }
        public string Comment { get; set; }
        public Nullable<int> TblJob { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public string User_Domain { get; set; }
        public string User_Win_Login { get; set; }
        public Nullable<short> CurrLang { get; set; }
        public Nullable<int> ActiveStore { get; set; }
        public Nullable<int> RegNo { get; set; }
        public string AllowedStores { get; set; }
        public Nullable<int> WFM_DOMAINID { get; set; }
        public string AxId { get; set; }
        public string AxName { get; set; }
        public Nullable<int> PrintingCode { get; set; }
        public Nullable<int> TblCompany { get; set; }
        public Nullable<int> TblPosition { get; set; }
        public Nullable<int> TblCompanySecondary { get; set; }
        public string PictureUrl { get; set; }
    
        public Collection<TblAdjustmentHeader> TblAdjustmentHeaders { get; set; }
        public Collection<TblAdjustmentHeader> TblAdjustmentHeaders1 { get; set; }
        public Collection<TblAuthWarehouse> TblAuthWarehouses { get; set; }
        public Collection<TblTransferHeader> TblTransferHeaders { get; set; }
        public Collection<TblTransferHeader> TblTransferHeaders1 { get; set; }
        public Collection<TblTransferHeader> TblTransferHeaders2 { get; set; }
    }
}
