//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.DataLayer
{
    using System;
    using System.Collections.Generic;using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    
    
    //[DataContract]
    public partial class TblAuthWarehouse : PropertiesViewModelBase
    {
        public int Iserial { get; set; }
        public int WarehouseIserial { get; set; }
        public int AuthUserIserial { get; set; }
        public short PermissionType { get; set; }
    
        public TblAuthUser TblAuthUser { get; set; }
        public TblWarehouse TblWarehouse { get; set; }
    }
}
