//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.DataLayer
{
    using System;
    using System.Collections.Generic;using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    
    
    //[DataContract]
    public partial class TblColor : PropertiesViewModelBase
    {
        public TblColor()
        {
            this.TblItemDims = new Collection<TblItemDim>();
            this.TblTradeAgreementDetails = new Collection<TblTradeAgreementDetail>();
        }
    
        public int Iserial { get; set; }
        public string Code { get; set; }
        public string Aname { get; set; }
        public string Ename { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> TblLkpColorGroup { get; set; }
        public Nullable<double> DefaultPrice { get; set; }
        public Nullable<int> ColorItemType { get; set; }
    
        public Collection<TblItemDim> TblItemDims { get; set; }
        public Collection<TblTradeAgreementDetail> TblTradeAgreementDetails { get; set; }
    }
}
