//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.DataLayer
{
    using System;
    using System.Collections.Generic;using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    
    
    //[DataContract]
    public partial class TblInventType : PropertiesViewModelBase
    {
        public TblInventType()
        {
            this.TblInventTrans = new Collection<TblInventTran>();
            this.TblSalesIssueHeaders = new Collection<TblSalesIssueHeader>();
        }
    
        public int Iserial { get; set; }
        public string Code { get; set; }
        public string Ename { get; set; }
        public string Aname { get; set; }
        public Nullable<short> Nature { get; set; }
        public string ShortCode { get; set; }
    
        public Collection<TblInventTran> TblInventTrans { get; set; }
        public Collection<TblSalesIssueHeader> TblSalesIssueHeaders { get; set; }
    }
}
