//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.DataLayer
{
    using System;
    using System.Collections.Generic;using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    
    
    //[DataContract]
    public partial class TblSalesIssueHeader : PropertiesViewModelBase
    {
        public TblSalesIssueHeader()
        {
            this.TblSalesIssueDetails = new Collection<TblSalesIssueDetail>();
            this.TblSalesOrderRequestInvoiceDetails = new Collection<TblSalesOrderRequestInvoiceDetail>();
        }
    
        public int Iserial { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string DocCode { get; set; }
        public string RefNo { get; set; }
        public string Notes { get; set; }
        public int TblJournalAccountType { get; set; }
        public int EntityAccount { get; set; }
        public Nullable<int> TblSalesOrderHeaderRequest { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<int> TblWarehouse { get; set; }
        public int TblInventType { get; set; }
    
        public TblInventType TblInventType1 { get; set; }
        public Collection<TblSalesIssueDetail> TblSalesIssueDetails { get; set; }
        public TblWarehouse TblWarehouse1 { get; set; }
        public Collection<TblSalesOrderRequestInvoiceDetail> TblSalesOrderRequestInvoiceDetails { get; set; }
        public TblSalesOrderHeaderRequest TblSalesOrderHeaderRequest1 { get; set; }
    }
}
