//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.DataLayer
{
    using System;
    using System.Collections.Generic;using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    
    
    //[DataContract]
    public partial class TblSequenceProduction : PropertiesViewModelBase
    {
        public int Iserial { get; set; }
        public string Code { get; set; }
        public int Lowest { get; set; }
        public int Highest { get; set; }
        public int NextRec { get; set; }
        public string Format { get; set; }
        public Nullable<int> NumberOfInt { get; set; }
        public bool Manual { get; set; }
        public bool UseDateTime { get; set; }
    }
}
