//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.DataLayer
{
    using System;
    using System.Collections.Generic;using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    
    
    //[DataContract]
    public partial class TblSalesOrderHeaderRequest : PropertiesViewModelBase
    {
        public TblSalesOrderHeaderRequest()
        {
            this.TblSalesIssueHeaders = new Collection<TblSalesIssueHeader>();
            this.TblSalesOrderDetailRequests = new Collection<TblSalesOrderDetailRequest>();
        }
    
        public int Iserial { get; set; }
        public string Code { get; set; }
        public int TblJournalAccountType { get; set; }
        public int EntityAccount { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> ShippingDate { get; set; }
        public string AxMethodOfPaymentCode { get; set; }
        public string AxTermOfPaymentCode { get; set; }
        public bool Status { get; set; }
        public Nullable<int> TblWarehouse { get; set; }
        public Nullable<int> TblCurrency { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<int> TblSalesPerson { get; set; }
    
        public Collection<TblSalesIssueHeader> TblSalesIssueHeaders { get; set; }
        public Collection<TblSalesOrderDetailRequest> TblSalesOrderDetailRequests { get; set; }
        public TblWarehouse TblWarehouse1 { get; set; }
    }
}
