//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.DataLayer
{
    using System;
    using System.Collections.Generic;using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    
    
    //[DataContract]
    public partial class TblTradeAgreementHeader : PropertiesViewModelBase
    {
        public TblTradeAgreementHeader()
        {
            this.TblTradeAgreementDetails = new Collection<TblTradeAgreementDetail>();
        }
    
        public int Iserial { get; set; }
        public string Vendor { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
    
        public Collection<TblTradeAgreementDetail> TblTradeAgreementDetails { get; set; }
    }
}
