//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.DataLayer
{
    using System;
    using System.Collections.Generic;using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    
    
    //[DataContract]
    public partial class TblTradeAgreementDetail : PropertiesViewModelBase
    {
        public int Iserial { get; set; }
        public int TblTradeAgreementHeader { get; set; }
        public int ItemCode { get; set; }
        public Nullable<int> TblColor { get; set; }
        public string AccSize { get; set; }
        public float Price { get; set; }
        public string ItemType { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> Days { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<int> TblVendorPurchaseGroup { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public double ShippingPercentage { get; set; }
        public double CustomsPercentage { get; set; }
        public double SalesPercentage { get; set; }
        public string SupplierColorCode { get; set; }
        public string Pantone { get; set; }
    
        public TblColor TblColor1 { get; set; }
        public TblTradeAgreementHeader TblTradeAgreementHeader1 { get; set; }
    }
}
