//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.DataLayer
{
    using System;
    using System.Collections.Generic;using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    
    
    //[DataContract]
    public partial class TblWarehouse : PropertiesViewModelBase
    {
        public TblWarehouse()
        {
            this.TblAdjustmentHeaders = new Collection<TblAdjustmentHeader>();
            this.TblAuthWarehouses = new Collection<TblAuthWarehouse>();
            this.TblTransferHeaders = new Collection<TblTransferHeader>();
            this.TblTransferHeaders1 = new Collection<TblTransferHeader>();
            this.TblInventTrans = new Collection<TblInventTran>();
            this.TblSalesIssueHeaders = new Collection<TblSalesIssueHeader>();
            this.TblSalesOrderHeaderRequests = new Collection<TblSalesOrderHeaderRequest>();
        }
    
        public int Iserial { get; set; }
        public string Code { get; set; }
        public string Ename { get; set; }
        public string Aname { get; set; }
        public Nullable<int> TblSite { get; set; }
        public Nullable<int> RetailCompany { get; set; }
        public Nullable<int> Receive { get; set; }
        public Nullable<int> RetReceive { get; set; }
        public Nullable<int> AdjustIn { get; set; }
        public Nullable<int> AdjustOut { get; set; }
        public Nullable<int> TransferIn { get; set; }
        public Nullable<int> TransferOut { get; set; }
        public Nullable<int> Sales { get; set; }
        public Nullable<int> RetSales { get; set; }
        public Nullable<int> Po { get; set; }
        public string Address { get; set; }
    
        public Collection<TblAdjustmentHeader> TblAdjustmentHeaders { get; set; }
        public Collection<TblAuthWarehouse> TblAuthWarehouses { get; set; }
        public TblSite TblSite1 { get; set; }
        public Collection<TblTransferHeader> TblTransferHeaders { get; set; }
        public Collection<TblTransferHeader> TblTransferHeaders1 { get; set; }
        public Collection<TblInventTran> TblInventTrans { get; set; }
        public Collection<TblSalesIssueHeader> TblSalesIssueHeaders { get; set; }
        public Collection<TblSalesOrderHeaderRequest> TblSalesOrderHeaderRequests { get; set; }
    }
}
