//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.DataLayer
{
    using System;
    using System.Collections.Generic;using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    
    
    //[DataContract]
    public partial class TransferToVendorWarehouseView : PropertiesViewModelBase
    {
        public string ServiceCode { get; set; }
        public string ServiceName { get; set; }
        public string Notes { get; set; }
        public string Vendor { get; set; }
        public string Location { get; set; }
        public int TransactionType { get; set; }
        public int TransId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public int DyeingProductionOrder { get; set; }
        public bool Posted { get; set; }
        public string WareHouse { get; set; }
        public string VendorTransaction { get; set; }
        public int BatchNo { get; set; }
        public string Color { get; set; }
        public int DyeingClass { get; set; }
        public string Unit { get; set; }
        public double CalculatedTotalQty { get; set; }
        public string FabricCode { get; set; }
    }
}
