//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.DataLayer
{
    using System;
    using System.Collections.Generic;using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    
    
    //[DataContract]
    public partial class v_RouteCardDetails_SizeInfo : PropertiesViewModelBase
    {
        public int Iserial { get; set; }
        public string Size { get; set; }
        public Nullable<int> SizeQuantity { get; set; }
        public int Trans_TransactionHeader { get; set; }
        public int RoutGroupID { get; set; }
        public int Direction { get; set; }
        public string Degree { get; set; }
        public int TblColor { get; set; }
        public string ObjectIndex { get; set; }
    }
}
