//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Runtime.Serialization;
    
    public partial class TblAdjustmentTempDetailSearch : PropertiesViewModelBase
    {
        string itemDimIserial, itemCode, itemName, colorCode, size, batchNo, availableQuantity, countedQuantity,
            differenceQuantity;

        public string BatchNo
        {
            get { return batchNo; }
            set { batchNo = value; RaisePropertyChanged(nameof(BatchNo)); }
        }
        public string ColorCode
        {
            get { return colorCode; }
            set { colorCode = value; RaisePropertyChanged(nameof(ColorCode)); }
        }
        public string ItemCode
        {
            get { return itemCode; }
            set { itemCode = value; RaisePropertyChanged(nameof(ItemCode)); }
        }
        public string ItemName
        {
            get { return itemName; }
            set { itemName = value; RaisePropertyChanged(nameof(ItemName)); }
        }
        public string Size
        {
            get { return size; }
            set { size = value; RaisePropertyChanged(nameof(Size)); }
        }

        public string ItemDimIserialStr
        {
            get { return itemDimIserial; }
            set { itemDimIserial = value; RaisePropertyChanged(nameof(ItemDimIserialStr)); }
        }
        public int ItemDimIserial
        {
            get { return Convert.ToInt32(itemDimIserial); }
        }
        public string AvailableQuantityStr
        {
            get { return availableQuantity; }
            set { availableQuantity = value; RaisePropertyChanged(nameof(AvailableQuantityStr)); }
        }
        public decimal AvailableQuantity
        {
            get { return Convert.ToDecimal(availableQuantity); }
        }
        public string CountedQuantityStr
        {
            get { return countedQuantity; }
            set { countedQuantity = value; RaisePropertyChanged(nameof(CountedQuantityStr)); }
        }
        public decimal CountedQuantity
        {
            get { return Convert.ToDecimal(countedQuantity); }
        }
        public string DifferenceQuantityStr
        {
            get { return differenceQuantity; }
            set { differenceQuantity = value; RaisePropertyChanged(nameof(DifferenceQuantityStr)); }
        }
        public decimal DifferenceQuantity
        {
            get { return Convert.ToDecimal(differenceQuantity); }
        }
    }
}