//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.DataLayer
{
    using Models.LocalizationHelpers;
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel.DataAnnotations;

    public class TblTransferHeader : PropertiesViewModelBase
    {
        public TblTransferHeader()
        {
            this.TblTransferDetails = new Collection<TblTransferDetail>();
        }

        private int iserial, warehouseFrom, warehouseTo, createdBy;
        private string codeFrom = "";
        private string codeTo = "";
        private DateTime docDate = DateTime.Now, creationDate = DateTime.Now;
        private bool approved = false;
        private int? approvedBy;
        private DateTime? approveDate;
        private DateTime lastChangeDate;
        private int? lastChangeUser;
        private string notes;

        public int Iserial
        {
            get { return iserial; }
            set
            {
                if (ReferenceEquals(iserial, value) != true)
                {
                    iserial = value; RaisePropertyChanged(nameof(Iserial));
                }
            }
        }
        [Required(ErrorMessageResourceType = typeof(strings), ErrorMessageResourceName = nameof(strings.ReqStore))]
        public int WarehouseFrom
        {
            get { return warehouseFrom; }
            set
            {
                if (ReferenceEquals(warehouseFrom, value) != true)
                {
                    warehouseFrom = value;
                    //if (TransferDetails != null && TransferDetails.Count > 0)
                    //{ TransferDetails.Clear();TransferDetails.Add(new TblTransferDetailModel()); }
                    RaisePropertyChanged(nameof(WarehouseFrom));
                    //RaisePropertyChanged(nameof(TransferDetails));
                }
            }
        }
        public string CodeFrom
        {
            get { return codeFrom; }
            set
            {
                if (ReferenceEquals(codeFrom, value) != true)
                {
                    codeFrom = value; RaisePropertyChanged(nameof(CodeFrom));
                }
            }
        }
        [Required(ErrorMessageResourceType = typeof(strings), ErrorMessageResourceName = nameof(strings.ReqStore))]
        public int WarehouseTo
        {
            get { return warehouseTo; }
            set
            {
                if (ReferenceEquals(warehouseTo, value) != true)
                {
                    warehouseTo = value; RaisePropertyChanged(nameof(WarehouseTo));
                }
            }
        }
        public string CodeTo
        {
            get { return codeTo; }
            set
            {
                if (ReferenceEquals(codeTo, value) != true)
                {
                    codeTo = value; RaisePropertyChanged(nameof(CodeTo));
                }
            }
        }
        [Required(ErrorMessageResourceType = typeof(strings), ErrorMessageResourceName = nameof(strings.ReqDate))]
        public DateTime DocDate
        {
            get { return docDate; }
            set
            {
                if (ReferenceEquals(docDate, value) != true)
                {
                    docDate = value; RaisePropertyChanged(nameof(DocDate));
                }
            }
        }
        public int CreatedBy
        {
            get { return createdBy; }
            set
            {
                if (ReferenceEquals(createdBy, value) != true)
                {
                    createdBy = value; RaisePropertyChanged(nameof(CreatedBy));
                }
            }
        }
        public DateTime CreationDate
        {
            get { return creationDate; }
            set
            {
                if (ReferenceEquals(creationDate, value) != true)
                { creationDate = value; RaisePropertyChanged(nameof(CreationDate)); }
            }
        }
        public bool Approved
        {
            get { return approved; }
            set
            {
                if (ReferenceEquals(approved, value) != true)
                {
                    approved = value; RaisePropertyChanged(nameof(Approved));
                    //RaisePropertyChanged(nameof(TransferViewModel.CanApprove));
                }
            }
        }
        public int? ApprovedBy
        {
            get { return approvedBy; }
            set
            {
                if (ReferenceEquals(approvedBy, value) != true)
                {
                    approvedBy = value; RaisePropertyChanged(nameof(ApprovedBy));
                }
            }
        }
        public DateTime? ApproveDate
        {
            get { return approveDate; }
            set
            {
                if (ReferenceEquals(approveDate, value) != true)
                {
                    approveDate = value; RaisePropertyChanged(nameof(ApproveDate));
                }
            }
        }
        public DateTime LastChangeDate
        {
            get { return lastChangeDate; }
            set
            {
                if (ReferenceEquals(lastChangeDate, value) != true)
                {
                    lastChangeDate = value; RaisePropertyChanged(nameof(LastChangeDate));
                }
            }
        }
        public int? LastChangeUser
        {
            get { return lastChangeUser; }
            set
            {
                if (ReferenceEquals(lastChangeUser, value) != true)
                {
                    lastChangeUser = value; RaisePropertyChanged(nameof(LastChangeUser));
                }
            }
        }
        public string Notes
        {
            get { return notes; }
            set
            {
                if ((ReferenceEquals(notes, value) != true))
                {
                    notes = value; RaisePropertyChanged(nameof(Notes));
                }
            }
        }

        private TblAuthUser tblAuthUser;
        //[DataMember]
        public virtual TblAuthUser TblAuthUser
        {
            get { return tblAuthUser ?? (TblAuthUser = new TblAuthUser()); }
            set
            {
                if ((ReferenceEquals(tblAuthUser, value) != true))
                {
                    tblAuthUser = value; RaisePropertyChanged(nameof(TblAuthUser));
                }
            }
        }

        private TblAuthUser tblAuthUser1;
        //[DataMember]
        public virtual TblAuthUser TblAuthUser1
        {
            get { return tblAuthUser1 ?? (TblAuthUser1 = new TblAuthUser()); }
            set
            {
                if ((ReferenceEquals(tblAuthUser1, value) != true))
                {
                    tblAuthUser1 = value; RaisePropertyChanged(nameof(TblAuthUser1));
                }
            }
        }

        private TblAuthUser tblAuthUser2;
        //[DataMember]
        public virtual TblAuthUser TblAuthUser2
        {
            get { return tblAuthUser2 ?? (TblAuthUser2 = new TblAuthUser()); }
            set
            {
                if ((ReferenceEquals(tblAuthUser2, value) != true))
                {
                    tblAuthUser2 = value; RaisePropertyChanged(nameof(TblAuthUser2));
                }
            }
        }

        private TblWarehouse tblWarehouseFrom = null;
        public virtual TblWarehouse TblWarehouseFrom
        {
            get { return tblWarehouseFrom ?? (tblWarehouseFrom = new TblWarehouse()); }
            set
            {
                if ((ReferenceEquals(tblWarehouseFrom, value) != true))
                {
                    tblWarehouseFrom = value; RaisePropertyChanged(nameof(TblWarehouseFrom));
                }
            }
        }

        private TblWarehouse tblWarehouseTo;
        public virtual TblWarehouse TblWarehouseTo
        {
            get { return tblWarehouseTo ?? (tblWarehouseTo = new TblWarehouse()); }
            set
            {
                if ((ReferenceEquals(tblWarehouseTo, value) != true))
                {
                    tblWarehouseTo = value; RaisePropertyChanged(nameof(TblWarehouseTo));
                }
            }
        }

        private Collection<TblTransferDetail> transferDetails;
        public virtual Collection<TblTransferDetail> TblTransferDetails
        {
            get { return transferDetails ?? (TblTransferDetails = new Collection<TblTransferDetail>()); }
            set
            {
                if ((ReferenceEquals(transferDetails, value) != true))
                {
                    transferDetails = value; RaisePropertyChanged(nameof(TblTransferDetails));
                }
            }
        }

    }
}
