//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCWFM.Web.DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Runtime.Serialization;


    //[DataContract]
    public partial class TblSalesOrderDetailRequest : PropertiesViewModelBase
    {
        public TblSalesOrderDetailRequest()
        {
            this.TblSalesIssueDetails = new Collection<TblSalesIssueDetail>();
        }


        private int iserial;
        //[DataMember]
        public int Iserial
        {
            get { return iserial; }
            set
            {
                iserial = value; RaisePropertyChanged(nameof(Iserial));
            }
        }

        private Nullable<int> tblSalesOrderHeaderRequest;
        //[DataMember]
        public Nullable<int> TblSalesOrderHeaderRequest
        {
            get { return tblSalesOrderHeaderRequest; }
            set
            {
                tblSalesOrderHeaderRequest = value; RaisePropertyChanged(nameof(TblSalesOrderHeaderRequest));
            }
        }

        private int tblItemDim;
        //[DataMember]
        public int TblItemDim
        {
            get { return tblItemDim; }
            set
            {
                tblItemDim = value; RaisePropertyChanged(nameof(TblItemDim));
            }
        }

        private string unit;
        //[DataMember]
        public string Unit
        {
            get { return unit; }
            set
            {
                unit = value; RaisePropertyChanged(nameof(Unit));
            }
        }


        private Web.DataLayer.ItemDimensionSearchModel itemTransfer;
        public virtual Web.DataLayer.ItemDimensionSearchModel ItemTransfer
        {
            get { return itemTransfer ?? (itemTransfer = new Web.DataLayer.ItemDimensionSearchModel()); }
            set
            {
                if ((ReferenceEquals(itemTransfer, value) != true))
                {
                    itemTransfer = value; RaisePropertyChanged(nameof(itemTransfer));
                }
            }
        }
        private decimal? qty;

        //[DataMember]
        public decimal? Qty
        {
            get { return qty; }
            set
            {
                qty = value; RaisePropertyChanged(nameof(Qty));
                Total = qty * price;
            }
        }

        private decimal? price;
        //[DataMember]
        public Nullable<decimal> Price
        {
            get { return price; }
            set
            {
                price = value; RaisePropertyChanged(nameof(Price));
                Total = qty * price;
            }

        }

        private decimal? _Total;

        public decimal? Total
        {
            get { return _Total; }
            set { _Total = value; RaisePropertyChanged("Total"); }
        }

        private Nullable<decimal> basicPrice;
        //[DataMember]
        public Nullable<decimal> BasicPrice
        {
            get { return basicPrice; }
            set
            {
                basicPrice = value; RaisePropertyChanged(nameof(BasicPrice));
            }
        }

        private Nullable<decimal> receiveNow;
        //[DataMember]
        public Nullable<decimal> ReceiveNow
        {
            get { return receiveNow; }
            set
            {
                receiveNow = value; RaisePropertyChanged(nameof(ReceiveNow));
            }
        }

        private Nullable<System.DateTime> deliveryDate;
        //[DataMember]
        public Nullable<System.DateTime> DeliveryDate
        {
            get { return deliveryDate; }
            set
            {
                deliveryDate = value; RaisePropertyChanged(nameof(DeliveryDate));
            }
        }

        private Nullable<System.DateTime> shippingDate;
        //[DataMember]
        public Nullable<System.DateTime> ShippingDate
        {
            get { return shippingDate; }
            set
            {
                shippingDate = value; RaisePropertyChanged(nameof(ShippingDate));
            }
        }


        private TblItemDim tblItemDim1;
        //[DataMember]
        public virtual TblItemDim TblItemDim1
        {
            get { return tblItemDim1; }
            set
            {
                if ((ReferenceEquals(tblItemDim1, value) != true))
                {
                    tblItemDim1 = value; RaisePropertyChanged(nameof(TblItemDim1));
                }
            }
        }

        private Collection<TblSalesIssueDetail> tblSalesIssueDetails;
        //[DataMember]
        public virtual Collection<TblSalesIssueDetail> TblSalesIssueDetails
        {
            get { return tblSalesIssueDetails; }
            set
            {
                if ((ReferenceEquals(tblSalesIssueDetails, value) != true))
                {
                    tblSalesIssueDetails = value; RaisePropertyChanged(nameof(TblSalesIssueDetails));
                }
            }
        }

        private TblSalesOrderHeaderRequest tblSalesOrderHeaderRequest1;
        //[DataMember]
        public virtual TblSalesOrderHeaderRequest TblSalesOrderHeaderRequest1
        {
            get { return tblSalesOrderHeaderRequest1; }
            set
            {
                if ((ReferenceEquals(tblSalesOrderHeaderRequest1, value) != true))
                {
                    tblSalesOrderHeaderRequest1 = value; RaisePropertyChanged(nameof(TblSalesOrderHeaderRequest1));
                }
            }
        }
    }
}